// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { Side } from "./Side";

/**
 * Participant info in a group match room.
 */
export type GroupMatchPeer = { 
/**
 * Unique identifier for this participant within the match, assigned by the
 * server. Used to key WebRTC mesh peers and route signals. Unlike `user_id`,
 * it is unique even when several guests (user_id 0) share a match.
 */
peerId: number, userId: number, email?: string, country?: string, role: Role, 
/**
 * Same pre-match group as the receiver (`Local`) or the opposing party (`Remote`).
 */
side?: Side, };
