// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicUser } from "./PublicUser";

export type GroupMessage = { id: number, groupId: number, senderId: number, text: string, createdAt: string, sender?: PublicUser, };
