// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitationStatus } from "./InvitationStatus";
import type { PublicUser } from "./PublicUser";

/**
 * One entry of `invitation:list`.
 */
export type InvitationEntry = { id: number, inviter: PublicUser, roomId: string, status: InvitationStatus, expiresAt: string, };
