// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gender } from "./Gender";
import type { MatchMode } from "./MatchMode";
import type { MatchScope } from "./MatchScope";

export type MatchPreferences = { country: string, language: string, gender: Gender, lookingFor: Gender, interests: Array<string>, allowMatchWithSameUsers: boolean, mode: MatchMode, matchScope: MatchScope, };
