export type { SocketLike, QueuePeer, Room, GroupRoom } from './types'
export {
  normalizePreferences,
  joinQueue,
  queueStats,
  fullRemove,
  send,
  blockPair,
  unblockPair,
  getSocketForUser,
  getAllSocketsForUser,
  registerUserSocket,
  unregisterUserSocket,
  getSocketUserId,
  createGroupMatchRoom,
  getGroupRoom,
  getGroupRoomById,
  addParticipantToGroup,
  startGroupMatch,
  matchUsers,
  getPartnerUserId,
  getPartner,
  getMeta,
  getRoom,
  heartbeat,
  removeFromQueue,
  leaveRoom,
  leaveGroup,
  hydrateBlocks,
  rematchCooldownMs,
  blockedPairCount,
  isBlockedPair,
  getUserSocketDebug,
} from './core'
